# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 八尾自在
email: baweizz@163.com
description: > # this means to ignore newlines until "baseurl:"
  Android开发以及其他各种探索.
baseurl: "/bawei" # the subpath of your site, e.g. /blog
url: "http://bithuoche.com" # the base hostname & protocol for your site
github_username:  bwzz

# Build settings
markdown: kramdown
